### ISSUE TITLE
DaggerAdvancedAchievementsComponent build path

### ISSUE THREAD

**Issue by vanduck241** [PyvesB/AdvancedAchievements#555]
Hello there!  i just want to use your AACH plugin as an API to code my minigame plugin. Just imported it and then: 
![ảnh](https://user-images.githubusercontent.com/46965131/60861346-56d84280-a244-11e9-9626-fb01408d3fbb.png)

you said "Add target/generated-sources/annotations to your build path" but im still dont understand.

im just started to learn how to code a plugin few months ago and still dont know how exactly how it works btw. sry for my bad english ~_~

**Comment by PyvesB** [comment]
Hello @vanduck241,

In Eclipse, right click on the _advanced-achievements-plugin_ module, select _Properties_, then _Java Build Path_. In the _Source_ tab, click _Add Folder..._ and select _target/generated-sources/annotations_. This should resolve the compilation issue.

Let me know if this helps! 😉 

Cheers,

Pyves

**Comment by vanduck241** [comment]
i dont know, im feel dumb right now. still cant find out target/generated-sources/annotations ~ . ~

![ảnh](https://user-images.githubusercontent.com/46965131/60940875-3fae5900-a307-11e9-80d4-63f42307e07a.png)
![ảnh](https://user-images.githubusercontent.com/46965131/60940937-7ab08c80-a307-11e9-958f-6fc5524f9a04.png)

**Comment by PyvesB** [comment]
Have you tried running `mvn clean install` on the project first?

**Comment by vanduck241** [comment]
i did
![ảnh](https://user-images.githubusercontent.com/46965131/60956763-a2b2e680-a32d-11e9-8233-83f8e01e37dd.png)

**Comment by PyvesB** [comment]
You only ran the `clean` target, not the `install` one.

**Comment by vanduck241** [comment]
its `clean` target

**Comment by PyvesB** [comment]
Run the `install`one! 😀

**Comment by vanduck241** [comment]
oh, just ran the install one and got this error:
`[ERROR] Failed to execute goal on project advanced-achievements-plugin: Could not resolve dependencies for project com.hm.achievement:advanced-achievements-plugin:jar:5.12.3: Failure to find com.hm.achievement:advanced-achievements-api:jar:1.2.0 in https://hub.spigotmc.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of bukkit-repo has elapsed or updates are forced`

i think the problem is there is a missing aach-api jar file

**Comment by vanduck241** [comment]
problem solved, thank you very much for your greate supporting.

**Comment by PyvesB** [comment]
You're welcome!
