### ISSUE TITLE
TimePlayed not given correctly? 

### ISSUE THREAD

**Issue by LifelessNerd** [PyvesB/AdvancedAchievements#643]
Hey there,

I really enjoy your plugin, but I'm having an issue with the PlayedTime category.
It might just be because I'm dumb though.
Here's the config thingy:

> # Amount of time played on the server (in hours, use integers).
> PlayedTime:
>   '24':
>     Goal: Play for 1 day.
>     Message: §6You played for 1 day on the server!
>     Name: playedtime_24
>     DisplayName: Nolife I
>   '48':
>     Goal: Play for 2 days.
>     Message: §6You played for 2 days on the server!
>     Name: playedtime_48
>     DisplayName: Nolife II
>   '72':
>     Goal: Play for 3 days.
>     Message: §6You played for 3 days on the server!
>     Name: playedtime_72
>     DisplayName: Nolife III
> 

Whenever I add 1 score to a player, all 3 achievements are triggered on the same exact moment.
The reason I want to add a score is because I already have the scoreboard (within vanilla MC) TimePlayed, but I want to convert it into the AACH stat. (with some ticks to hours calculation)
Is there something I'm doing wrong? Please let me know if you need the entire config.yml
Thanks!

Luka

**Comment by PyvesB** [comment]
Hi @LifelessNerd , are you using the latest version of the plugin?

**Comment by LifelessNerd** [comment]
Thought I was, turns out Server.pro is a little behind.
Fixed it with the last update.
Thanks!

**Comment by LifelessNerd** [comment]
Heyo,

Thought the issue was fixed when I added some score to a player, but it turns out it doesn't get added when I take a look inside /aach list. 

Any idea why this may be?

**Comment by PyvesB** [comment]
There probably still is a bug with _/aach add_ for the `PlayedTime` category. Will look into it again!

**Comment by LifelessNerd** [comment]
Thank you!

**Comment by MCHalfAssed** [comment]
I am also still having this issue on the latest update, 5.13.4. Not seeing any errors in the log when trying to use the  /aach add command when using it with the PlayedTime achievement category - Just nothing happens sadly.
